add associations
EyasuTeshome/school-library pull request #3
Opened 2022-10-06 18:40 UTC by EyasuTeshome

In this PR:
- Created a class classroom.
- Created the has-many/belongs-to relationship between Classroom and Student.
- Created a class Book.
- Created a class Rental.
- Created the many-to-many relationship between Person and Book using the intermediate class Rental.

2022-10-06 18:48 UTC, Ismailco reviewed
Hi @EyasuTeshome, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no professional documentation, kindly consider using the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by microverse to Create your README file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-06 19:47 UTC, tufoinnkuo10 requested changes
Hi @EyasuTeshome 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-06 19:47 UTC, tufoinnkuo10 commented on school/book.rb
> +  attr_accessor :title, :author
- [ ] kindly add @rentals as it is the class used to set the relationship between person and book

2022-10-06 19:47 UTC, tufoinnkuo10 commented on school/rental.rb
> +class Classroom
- [ ] Great job. kindly add a rental class
- [ ] kindly add its setters and getters for the @date instance variable, and ensure that the @date instance variable is initialized in the constructor

2022-10-06 19:47 UTC, tufoinnkuo10 commented on school/person.rb
> +
- [ ] it is rental of a book. The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association. something like this
```ruby
def rent_book(book, date)
    Rental.new(date, book, self)
  end
```

2022-10-06 19:47 UTC, tufoinnkuo10 commented on school/student.rb
> +
- [ ] also add classroom to class student
`attr_reader :classroom`

2022-10-07 10:48 UTC, KDlamini approved these changes
### Hi @EyasuTeshome 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ All required classes present
✔️ Inheritance and associations implemented
✔️ Good PR description
✔️ No linter errors

# Status: Approved ✔️ 

![simon](https://user-images.githubusercontent.com/38088818/194536360-0c12fe9c-ca01-43c7-98f0-7d6de0e56be3.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 13:35 UTC, merged